project:
  type: website
  output-dir: "preview" # for quarto preview. build.R supplies per-year output dir
  resources:
    - logos/**
  render:
    - "*.qmd"
    - "!LICENSE"
    - "!qgis/"
    - "!docs/"
execute:
  freeze: false

format:
  html:
    toc: true
    theme:
      - materia
      - styles.scss
    sidebar: false
website:
  navbar:
    pinned: true
    left:
      - text: "Start"
        href: index.html

      - ueberblick.qmd

      - text: "Regionen"
        menu:
          - region/ostwerk.qmd
          - region/nord.qmd
          - region/sachsen.qmd
          - region/thueringen.qmd
          - region/sueden.qmd
          - region/westbund.qmd

      - themen.qmd
      - wirkung-pg.qmd
      - trends.qmd

    right:
      - text: "Hilfe"
        href: hilfe.html
      - icon: github
        href: https://github.com/
        aria-label: GitHub
  sidebar:
    - title: "main"
      collapse-level: 2
      contents:
        - text: "Start"
          href: index.qmd
        - ueberblick.qmd
        - themen.qmd
        - wirkung-pg.qmd
        - trends.qmd
  favicon: logos/tensing.ico
  page-navigation: true
