project:
  type: website
  output-dir: _site
  pre-render: 
  - R/utils.R
  - R/pre_render.R
  - config/viz_config.R
  - R/quarto-utils.R
  render:
  - '!LICENSE'
  - "!dump.qmd"
  - '*qmd'
  - "!qgis/"
execute:
  freeze: auto
format:
  html:
    toc: true
    theme:
      - materia
      - styles.scss
website:
  navbar:
    left:
    - text: Start
      href: index.html
    - ueberblick.qmd
    - text: Regionen
      menu:
      - href: region/ostwerk.qmd
      - href: region/nord.qmd
      - href: region/sachsen.qmd
      - href: region/thueringen.qmd
      - href: region/sueden.qmd
    #  - href: region/westbund.qmd
    - themen.qmd
    - wirkung-pg.qmd
    - trends.qmd
    right:
    - text: Hilfe
      href: hilfe.html
    - icon: github
      href: https://github.com/
      aria-label: GitHub
  page-navigation: true
